---
- name: Install and setup Filebeat
  hosts: webservers
  become: yes
  tasks:

  - name: Download Filebeat.deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.1-a>

  - name: Install Filebeat.deb
    command: dpkg -i filebeat-7.6.1-amd64.deb

  - name: drop in filebeat.yml
    copy:
      src: /etc/ansible/files/filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml

  - name: Enable and configure system module
    command: filebeat modules enable system

  - name: Setup filebeat
    command: filebeat setup

  - name: Start filebeat service
    command: service filebeat start

  - name: Start filebeat on boot
    systemd:
      name: filebeat.service
      enabled: yes

- name: Install and setup MetricBeat
  hosts: webservers
  become: yes
  tasks:

  - name: Download Metricbeat
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4>

  - name: Install Metricbeat
    command: dpkg -i metricbeat-7.4.0-amd64.deb

  - name: drop in metricbeat.yml
    copy:
      src: /etc/ansible/files/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: Enable and configure system module
    command: metricbeat modules enable docker

  - name: Setup Metricbeat
    command: metricbeat setup -e

  - name: Enable Metricbeat on boot
    systemd:
      name: metricbeat.service
      enabled: yes
